services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

  db:
    image: postgres:latest
    container_name: library-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: